### ISSUE TITLE
Parse error when loading frozen model

### ISSUE THREAD

**Issue by walteryu** [isaychris/litter-detection-tensorflow#1]
Dear Team FixIT and Keep America Beautiful - Great work and thanks for sharing this project! I am following steps in the notebook but ran into a parse error when loading the frozen model with the ParseFromString function which looks like it cannot decode the file into a graph.

My code is deployed within a Google Colab [notebook](https://colab.research.google.com/drive/1-cFB7I8sY02Yo5A833YPZ4f17yMz7pOG) which includes troubleshooting efforts after reading through the project documentation, tutorials and StackOverflow. Listed below is the full stack trace; any insights on how to load the model would be appreciated and thanks in advance for your help.

Full Stack Trace:
---------------------------------------------------------------------------
ParseError                                Traceback (most recent call last)
<ipython-input-2-38c109b66c6a> in <module>()
    183     # text_format.Merge(proto_b, graph_def)
    184     # Error: Merge/ParseFromString both throwing parse errors
--> 185     text_format.Merge(serialized_graph, od_graph_def)
    186 
    187     # od_graph_def.ParseFromString(serialized_graph)

/usr/local/lib/python3.6/dist-packages/google/protobuf/text_format.py in Merge(text, message, allow_unknown_extension, allow_field_number, descriptor_pool)
    534       allow_unknown_extension,
    535       allow_field_number,
--> 536       descriptor_pool=descriptor_pool)
    537 
    538 

/usr/local/lib/python3.6/dist-packages/google/protobuf/text_format.py in MergeLines(lines, message, allow_unknown_extension, allow_field_number, descriptor_pool)
    588                    allow_field_number,
    589                    descriptor_pool=descriptor_pool)
--> 590   return parser.MergeLines(lines, message)
    591 
    592 

/usr/local/lib/python3.6/dist-packages/google/protobuf/text_format.py in MergeLines(self, lines, message)
    621     """Merges a text representation of a protocol message into a message."""
    622     self._allow_multiple_scalars = True
--> 623     self._ParseOrMerge(lines, message)
    624     return message
    625 

/usr/local/lib/python3.6/dist-packages/google/protobuf/text_format.py in _ParseOrMerge(self, lines, message)
    636     tokenizer = Tokenizer(lines)
    637     while not tokenizer.AtEnd():
--> 638       self._MergeField(tokenizer, message)
    639 
    640   def _MergeField(self, tokenizer, message):

/usr/local/lib/python3.6/dist-packages/google/protobuf/text_format.py in _MergeField(self, tokenizer, message)
    747         merger = self._MergeMessageField
    748       else:
--> 749         tokenizer.Consume(':')
    750         merger = self._MergeScalarField
    751 

/usr/local/lib/python3.6/dist-packages/google/protobuf/text_format.py in Consume(self, token)
   1099     """
   1100     if not self.TryConsume(token):
-> 1101       raise self.ParseError('Expected "%s".' % token)
   1102 
   1103   def ConsumeComment(self):

ParseError: 1:9 : Expected ":".

**Comment by vincentcheng62** [comment]
You need to download author's model set here:
https://drive.google.com/file/d/1z-PaHvQ3UcjQJRv-3HrVgQudpgDnBtok/view?usp=sharing

**Comment by walteryu** [comment]
Vincent - Thanks for the link, and I will go ahead to try it out.

**Comment by murdockhou** [comment]
@walteryu hi, have you successfully run this code?

**Comment by walteryu** [comment]
@murdockhou Thanks for following up, though our team ended up using Azure Custom Vision for our project instead since it was better suited for the non-technical members. But otherwise, I have referred others interested in litter detection with AI to this repo; it is quite a comprehensive project!
